Ft add email verification and password reset
aceuganda/epilepsy-smart-server pull request #39
Opened 2023-05-26 07:10 UTC by MutegekiHenry

PR Checklist

## Description

- It adds three endpoints to perform user account verification and password reset via email. 

Pull branch and test the functionality in the following endpoints
- /users/reset_password/{token}
- /users/verify/{token}
- /users/verify

2023-05-26 07:15 UTC, MutegekiHenry commented
Password on slack

2023-05-31 13:16 UTC, Schade9 requested changes
I have noticed some changes that have to be made.

2023-05-31 13:16 UTC, Schade9 commented on app/routes/__init__.py
Some imports are missing in this file. `EmailVerificationRequest`.
`ResetPassword` should change to `ResetPasswordView`

2023-05-31 13:16 UTC, Schade9 commented on app/controllers/__init__.py
Change `ResetPassword` to `ResetPasswordView`
Add `UserEmailVerificationView` and `EmailVerificationRequest` imports

2023-05-31 13:16 UTC, Schade9 commented on app/controllers/user.py
Was VERIFICATION_SALT and MAIL_DEFAULT_SENDER added to the `config.py` file?
We have an error for verification salt when registering a user. line 57.

2023-06-08 22:00 UTC, Schade9 approved these changes

2023-06-19 13:16 UTC, merged